### ISSUE TITLE
fix links in quick start guide to api docs

### ISSUE THREAD

**Issue by makkus183** [heidelpay/php-payment-api#13]
the following links are not working on http://dev.heidelpay.com/quick-start-quide-php-payment-api/ : 

> Depending on the chosen payment method there are different transaction types that can be used. Please have a look inside the **payment method documentation.**

 (https://dev.heidelpay.de/php-api/docs/namespaces/Heidelpay.PhpApi.PaymentMethods.html)

> The heidelpay api supports a great amount of name spaces and parameters. Please have a look into the **ParameterGroup** documentation.

 (https://dev.heidelpay.de/php-api/docs/namespaces/Heidelpay.PhpApi.ParameterGroups.html)

**Comment by sixer1182** [comment]
Hi @makkus183,
thanks for your contribution.
The links are working now.

Have a nice day,
Simon
