### ISSUE TITLE
Is there any vue.js script for heidelpay 

### ISSUE THREAD

**Issue by ankitsingh30** [heidelpay/php-payment-api#21]
Is there any vue.js script for heidelpay. I am looking for heidelpay sdk in js.

**Comment by frostblogNet** [comment]
Hi @ankitsingh30,

the heidelpay system is not able to work headless yet. So you have to do an server to server request first. So currently we have to say there is no vue,js script. sorry.

Regards
Jens

**Comment by ankitsingh30** [comment]
Hi! @frostblogNet ,

Thanks for quick reply. Is there any alternative.

Regards
Ankit

**Comment by stevenobird** [comment]
Hi @ankitsingh30,

since our APIs are meant to be used server-to-server, there are no implementations for JS yet.

Best regards,
Stephano

**Comment by ankitsingh30** [comment]
@stevenobird ,

thanks
