### ISSUE TITLE
Exception for missing params

### ISSUE THREAD

**Issue by heidelpay-sp** [heidelpay/php-payment-api#24]
for credit and debitcard if an request is done without params
- paymentFrameOrigin
- preventAsyncRedirect
- cssPath
an exception should be thrown

**Comment by stevenobird** [comment]
We should not throw an Exception.
Instead we should not overwrite the values if they are equal the default parameters (e.g. null).

See https://github.com/heidelpay/php-payment-api/blob/master/lib/PaymentMethods/CreditCardPaymentMethod.php#L75 for example:

`$paymentFrameOrigin = null, $preventAsyncRedirect = 'FALSE', $cssPath = null`

Below we should add checks that determine if the arguments are equal to their default value - if not, call the corresponding setters.

**Comment by stevenobird** [comment]
Fixed with PR #25 - release early next week.
