### ISSUE TITLE
Correct request parameters to schedule recurring payments

### ISSUE THREAD

**Issue by Flynamic** [heidelpay/php-payment-api#30]
Which parameters are needed to schedule recurring payments (using payment code DD.SD)? It would be a good idea to implement this transaction type in the library if it's officially supported.

**Comment by frostblogNet** [comment]
Hello @Flynamic 

the current sdk is based on the post api, which does not support recurring payments. The only solution by now is you can schedule on your side and just send the debit on registration to our payment system.
