### ISSUE TITLE
How to read transactions from https://heidelpay.hpcgw.net/hip?

### ISSUE THREAD

**Issue by kaluzki** [heidelpay/php-payment-api#7]
Can this library be used to read transactions from an account at https://heidelpay.hpcgw.net/hip? Or is there any other way to do it?

**Comment by stevenobird** [comment]
Hi,

you can only send requests to create transactions and process incoming responses from the payment API.

For receiving transaction details by transaction id, our XML transactions API is your way to go.
To get its documentation, you can contact us at development@heidelpay.de

Best regards,
Stephano
